### ISSUE TITLE
Error: Class 'InfancyIt\LogRhythm\LogRhythmServiceProvider' not found  

### ISSUE THREAD

**Issue by dipu-bd** [infancyit/log-rhythm#1]
I am getting the following error after `composer require infancyit/log-rhythm`:
```
In ProviderRepository.php line 208:
                                                                  
  Class 'InfancyIt\LogRhythm\LogRhythmServiceProvider' not found  
```

**Configs**:
- PHP 7.2.11-3+ubuntu16.04.1+deb.sury.org+1
- Composer version 1.6.5
- laravel 5.5

**Comment by RafikFarhad** [comment]
The issue has been fixed. Please use latest version `1.2`
You can use this command to install the latest version:
`composer require infancyit/log-rhythm "^1.2"`
