### ISSUE TITLE
Provide a basic tutorial

### ISSUE THREAD

**Issue by dipu-bd** [infancyit/log-rhythm#2]
Can you update the `README.md` and provide some examples showing how can I use this package for logging?

**Comment by RafikFarhad** [comment]
Okay. I will.
But for now you can see this.
[Laravel Log](https://laravel.com/docs/5.7/logging#writing-log-messages)
You can log using Laravel default `Log` facades.
    `
    Log::emergency($message);
    Log::alert($message);
    Log::critical($message);
    Log::error($message);
    Log::warning($message);
    Log::notice($message);
    Log::info($message);
    Log::debug($message);
    `
